In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Book.csv")

In [4]:
df.head()

,Unnamed: 0,Ship Mode,First Class,Unnamed: 3,Unnamed: 4,Same Day,Unnamed: 6,Unnamed: 7,Second Class,Unnamed: 9,Unnamed: 10,Standard Class,Unnamed: 12,Unnamed: 13
0,NaN,Segment,Consumer,Corporate,Home Office,Consumer,Corporate,Home Office,Consumer,Corporate,Home Office,Consumer,Corporate,Home Office
1,Order ID,Order Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CA-2011-100293,41347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.056
3,CA-2011-100706,41624,NaN,NaN,NaN,NaN,NaN,NaN,129.44,NaN,NaN,NaN,NaN,NaN
4,CA-2011-100895,41427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605.47,NaN,NaN

In [5]:
df.shape

(825, 14)

In [6]:
df.columns

Index(['Unnamed: 0', 'Ship Mode', 'First Class', 'Unnamed: 3', 'Unnamed: 4',
       'Same Day', 'Unnamed: 6', 'Unnamed: 7', 'Second Class', 'Unnamed: 9',
       'Unnamed: 10', 'Standard Class', 'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 825 entries, 0 to 824
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      824 non-null    object
 1   Ship Mode       824 non-null    object
 2   First Class     74 non-null     object
 3   Unnamed: 3      42 non-null     object
 4   Unnamed: 4      14 non-null     object
 5   Same Day        30 non-null     object
 6   Unnamed: 6      7 non-null      object
 7   Unnamed: 7      8 non-null      object
 8   Second Class    93 non-null     object
 9   Unnamed: 9      52 non-null     object
 10  Unnamed: 10     25 non-null     object
 11  Standard Class  255 non-null    object
 12  Unnamed: 12     154 non-null    object
 13  Unnamed: 13     92 non-null     object
dtypes: object(14)
memory usage: 90.4+ KB

In [9]:
df.iloc[:2, :]

,Unnamed: 0,Ship Mode,First Class,Unnamed: 3,Unnamed: 4,Same Day,Unnamed: 6,Unnamed: 7,Second Class,Unnamed: 9,Unnamed: 10,Standard Class,Unnamed: 12,Unnamed: 13
0,NaN,Segment,Consumer,Corporate,Home Office,Consumer,Corporate,Home Office,Consumer,Corporate,Home Office,Consumer,Corporate,Home Office
1,Order ID,Order Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df["Unnamed: 0"].head(15)

0                NaN
1           Order ID
2     CA-2011-100293
3     CA-2011-100706
4     CA-2011-100895
5     CA-2011-100916
6     CA-2011-101266
7     CA-2011-101560
8     CA-2011-101770
9     CA-2011-102274
10    CA-2011-102673
11    CA-2011-102988
12    CA-2011-103317
13    CA-2011-103366
14    CA-2011-103807
Name: Unnamed: 0, dtype: object

In [11]:
df["Ship Mode"].head(15)

0        Segment
1     Order Date
2          41347
3          41624
4          41427
5          41568
6          41513
7          41606
8          41364
9          41599
10         41579
11         41369
12         41460
13         41289
14         41610
Name: Ship Mode, dtype: object

In [12]:
df.isnull().sum()

Unnamed: 0          1
Ship Mode           1
First Class       751
Unnamed: 3        783
Unnamed: 4        811
Same Day          795
Unnamed: 6        818
Unnamed: 7        817
Second Class      732
Unnamed: 9        773
Unnamed: 10       800
Standard Class    570
Unnamed: 12       671
Unnamed: 13       733
dtype: int64

In [14]:
df["First Class"].dropna().head(10)

0      Consumer
13       149.95
22        243.6
31        9.568
53         8.96
65         34.2
78       31.984
106      286.65
115      514.03
121     1000.95
Name: First Class, dtype: object

In [15]:
sales_cols = [
    "First Class", "Unnamed: 3", "Unnamed: 4",
    "Same Day", "Unnamed: 6", "Unnamed: 7",
    "Second Class", "Unnamed: 9", "Unnamed: 10",
    "Standard Class", "Unnamed: 12", "Unnamed: 13"
]

sales_check = df[sales_cols].apply(pd.to_numeric, errors="coerce")

sales_check.describe()

,First Class,Unnamed: 3,Unnamed: 4,Same Day,Unnamed: 6,Unnamed: 7,Second Class,Unnamed: 9,Unnamed: 10,Standard Class,Unnamed: 12,Unnamed: 13
count,73.000000,41.000000,13.000000,29.000000,6.00000,7.000000,92.000000,51.000000,24.000000,254.000000,153.000000,91.000000
mean,569.922548,1014.273512,1190.428615,560.855793,3302.43600,850.701714,1080.962054,1382.087490,732.593917,920.646728,731.278255,1203.266648
std,2440.803261,3256.300926,2175.118083,1502.242037,4484.72925,1177.706403,5255.130764,4930.601791,1759.042386,7346.221367,4543.001377,6206.566900
min,2.214000,2.896000,3.744000,10.272000,111.90400,7.968000,2.064000,3.760000,3.444000,2.610000,1.167000,3.760000
25%,34.200000,47.320000,121.780000,36.192000,276.53850,186.794000,32.005500,25.950000,62.554000,41.947000,30.336000,32.914000
50%,88.920000,242.546000,220.056000,107.830000,734.63700,259.290000,181.911000,342.240000,221.821500,183.870000,106.944000,141.960000
75%,348.560000,670.001000,771.800000,354.900000,6335.37750,1168.305000,714.023875,1129.897000,754.517500,549.543000,364.930000,492.287000
max,20802.173000,20792.607000,7737.786000,8132.409000,9907.30800,2977.456000,49724.254500,35243.231000,8791.127000,116922.134500,55942.786500,54748.632500

In [16]:
df.tail(5)

,Unnamed: 0,Ship Mode,First Class,Unnamed: 3,Unnamed: 4,Same Day,Unnamed: 6,Unnamed: 7,Second Class,Unnamed: 9,Unnamed: 10,Standard Class,Unnamed: 12,Unnamed: 13
820,US-2014-166611,42457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68.742,NaN
821,US-2014-167920,42713,NaN,NaN,NaN,NaN,NaN,NaN,1827.51,NaN,NaN,NaN,NaN,NaN
822,US-2014-168116,42678,NaN,NaN,NaN,NaN,8167.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN
823,US-2014-168690,42377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.808,NaN,NaN
824,Grand Total,NaN,20802.173,20792.607,7737.786,8132.409,9907.308,2977.456,49724.2545,35243.231,8791.127,116922.1345,55942.7865,54748.6325

In [17]:
df.iloc[2:824]["Unnamed: 0"].nunique()

822

In [18]:
df.iloc[2:824]["Unnamed: 0"].isna().sum()

np.int64(0)

In [19]:
df_data = df.iloc[2:824].copy().reset_index(drop=True)

In [20]:
df_data.shape

(822, 14)

In [21]:
df_data.head()

,Unnamed: 0,Ship Mode,First Class,Unnamed: 3,Unnamed: 4,Same Day,Unnamed: 6,Unnamed: 7,Second Class,Unnamed: 9,Unnamed: 10,Standard Class,Unnamed: 12,Unnamed: 13
0,CA-2011-100293,41347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.056
1,CA-2011-100706,41624,NaN,NaN,NaN,NaN,NaN,NaN,129.44,NaN,NaN,NaN,NaN,NaN
2,CA-2011-100895,41427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,605.47,NaN,NaN
3,CA-2011-100916,41568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,788.86,NaN
4,CA-2011-101266,41513,NaN,NaN,NaN,NaN,NaN,NaN,13.36,NaN,NaN,NaN,NaN,NaN

In [22]:
segment_shipmode = {
    "First Class": {
        "First Class": "Consumer",
        "Unnamed: 3": "Corporate",
        "Unnamed: 4": "Home Office"
    },
    "Same Day": {
        "Same Day": "Consumer",
        "Unnamed: 6": "Corporate",
        "Unnamed: 7": "Home Office"
    },
    "Second Class": {
        "Second Class": "Consumer",
        "Unnamed: 9": "Corporate",
        "Unnamed: 10": "Home Office"
    },
    "Standard Class": {
        "Standard Class": "Consumer",
        "Unnamed: 12": "Corporate",
        "Unnamed: 13": "Home Office"
    }
}

In [23]:
segment_shipmode

{'First Class': {'First Class': 'Consumer',
  'Unnamed: 3': 'Corporate',
  'Unnamed: 4': 'Home Office'},
 'Same Day': {'Same Day': 'Consumer',
  'Unnamed: 6': 'Corporate',
  'Unnamed: 7': 'Home Office'},
 'Second Class': {'Second Class': 'Consumer',
  'Unnamed: 9': 'Corporate',
  'Unnamed: 10': 'Home Office'},
 'Standard Class': {'Standard Class': 'Consumer',
  'Unnamed: 12': 'Corporate',
  'Unnamed: 13': 'Home Office'}}

In [24]:
records = []

for ship_mode, columns in segment_shipmode.items():
    for column, segment in columns.items():

        temp = df_data[["Unnamed: 0", "Ship Mode", column]].copy()

        temp.columns = ["Order ID", "Order Date", "Sales"]

        temp["Ship Mode"] = ship_mode
        temp["Segment"] = segment

        records.append(temp)

long_df = pd.concat(records, ignore_index=True)

long_df = long_df[
    ["Order ID", "Order Date", "Ship Mode", "Segment", "Sales"]
]

In [25]:
long_df.shape

(9864, 5)

In [26]:
long_df.head(15)

          Order ID Order Date    Ship Mode   Segment   Sales
0   CA-2011-100293      41347  First Class  Consumer     NaN
1   CA-2011-100706      41624  First Class  Consumer     NaN
2   CA-2011-100895      41427  First Class  Consumer     NaN
3   CA-2011-100916      41568  First Class  Consumer     NaN
4   CA-2011-101266      41513  First Class  Consumer     NaN
5   CA-2011-101560      41606  First Class  Consumer     NaN
6   CA-2011-101770      41364  First Class  Consumer     NaN
7   CA-2011-102274      41599  First Class  Consumer     NaN
8   CA-2011-102673      41579  First Class  Consumer     NaN
9   CA-2011-102988      41369  First Class  Consumer     NaN
10  CA-2011-103317      41460  First Class  Consumer     NaN
11  CA-2011-103366      41289  First Class  Consumer  149.95
12  CA-2011-103807      41610  First Class  Consumer     NaN
13  CA-2011-103989      41352  First Class  Consumer     NaN
14  CA-2011-104283      41452  First Class  Consumer     NaN

In [27]:
long_df.shape

(9864, 5)

In [28]:
long_df["Sales"].notna().sum()

np.int64(822)

In [29]:
long_df["Sales"].isna().sum()

np.int64(9042)

In [30]:
long_df = long_df.dropna(subset=["Sales"]).reset_index(drop=True)

In [31]:
long_df.shape

(822, 5)

In [32]:
long_df.head(20)

          Order ID Order Date    Ship Mode   Segment    Sales
0   CA-2011-103366      41289  First Class  Consumer   149.95
1   CA-2011-109043      41501  First Class  Consumer    243.6
2   CA-2011-113166      41632  First Class  Consumer    9.568
3   CA-2011-124023      41371  First Class  Consumer     8.96
4   CA-2011-130155      41413  First Class  Consumer     34.2
5   CA-2011-136861      41522  First Class  Consumer   31.984
6   CA-2011-153927      41498  First Class  Consumer   286.65
7   CA-2011-157784      41460  First Class  Consumer   514.03
8   CA-2011-160094      41394  First Class  Consumer  1000.95
9   CA-2011-164749      41356  First Class  Consumer    9.912
10  CA-2011-166730      41638  First Class  Consumer   39.128
11  CA-2012-102722      41747  First Class  Consumer    106.5
12  CA-2012-102778      41964  First Class  Consumer   18.176
13  CA-2012-117828      41996  First Class  Consumer   194.32
14  CA-2012-130218      41721  First Class  Consumer    59.48
15  CA-2012-132318      41942  First Class  Consumer   182.91
16  CA-2012-137974      41745  First Class  Consumer   2298.9
17  CA-2012-138625      41945  First Class  Consumer   197.72
18  CA-2012-141327      41973  First Class  Consumer  440.144
19  CA-2012-149300      41965  First Class  Consumer   32.985

In [33]:
long_df.shape

(822, 5)

In [34]:
long_df["Order Date"] = pd.to_numeric(
    long_df["Order Date"],
    errors="coerce"
)

In [35]:
long_df["Order Date"].dtype

dtype('int64')

In [36]:
long_df["Order Date"].head(10)

0    41289
1    41501
2    41632
3    41371
4    41413
5    41522
6    41498
7    41460
8    41394
9    41356
Name: Order Date, dtype: int64

In [37]:
long_df["Order Date"] = pd.to_datetime(
    long_df["Order Date"],
    unit="D",
    origin="1899-12-30"
)

In [38]:
long_df.head(20)

          Order ID Order Date    Ship Mode   Segment    Sales
0   CA-2011-103366 2013-01-15  First Class  Consumer   149.95
1   CA-2011-109043 2013-08-15  First Class  Consumer    243.6
2   CA-2011-113166 2013-12-24  First Class  Consumer    9.568
3   CA-2011-124023 2013-04-07  First Class  Consumer     8.96
4   CA-2011-130155 2013-05-19  First Class  Consumer     34.2
5   CA-2011-136861 2013-09-05  First Class  Consumer   31.984
6   CA-2011-153927 2013-08-12  First Class  Consumer   286.65
7   CA-2011-157784 2013-07-05  First Class  Consumer   514.03
8   CA-2011-160094 2013-04-30  First Class  Consumer  1000.95
9   CA-2011-164749 2013-03-23  First Class  Consumer    9.912
10  CA-2011-166730 2013-12-30  First Class  Consumer   39.128
11  CA-2012-102722 2014-04-18  First Class  Consumer    106.5
12  CA-2012-102778 2014-11-21  First Class  Consumer   18.176
13  CA-2012-117828 2014-12-23  First Class  Consumer   194.32
14  CA-2012-130218 2014-03-23  First Class  Consumer    59.48
15  CA-2012-132318 2014-10-30  First Class  Consumer   182.91
16  CA-2012-137974 2014-04-16  First Class  Consumer   2298.9
17  CA-2012-138625 2014-11-02  First Class  Consumer   197.72
18  CA-2012-141327 2014-11-30  First Class  Consumer  440.144
19  CA-2012-149300 2014-11-22  First Class  Consumer   32.985

In [39]:
long_df["Order Date"].dtype

dtype('<M8[ns]')

In [40]:
long_df["Sales"] = pd.to_numeric(
    long_df["Sales"],
    errors="coerce"
)

In [41]:
long_df["Sales"].dtype

dtype('float64')

In [42]:
long_df["Sales"].isna().sum()

np.int64(0)

In [43]:
long_df.dtypes

Order ID              object
Order Date    datetime64[ns]
Ship Mode             object
Segment               object
Sales                float64
dtype: object

In [44]:
long_df.isna().sum()

Order ID      0
Order Date    0
Ship Mode     0
Segment       0
Sales         0
dtype: int64

In [45]:
long_df.duplicated().sum()

np.int64(0)

In [46]:
print("Ship Modes:")
print(long_df["Ship Mode"].unique())

print("\nSegments:")
print(long_df["Segment"].unique())

Ship Modes:
['First Class' 'Same Day' 'Second Class' 'Standard Class']

Segments:
['Consumer' 'Corporate' 'Home Office']

In [47]:
print("Zero Sales:", (long_df["Sales"] == 0).sum())
print("Negative Sales:", (long_df["Sales"] < 0).sum())

Zero Sales: 0
Negative Sales: 0

In [48]:
long_df["Sales"].describe()

count      822.00000
mean       476.54733
std       1144.58992
min          1.16700
25%         34.54050
50%        159.97500
75%        536.11000
max      23661.22800
Name: Sales, dtype: float64

In [49]:
Q1 = long_df["Sales"].quantile(0.25)
Q3 = long_df["Sales"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Q1: 34.540499999999994
Q3: 536.11
IQR: 501.5695
Lower Bound: -717.81375
Upper Bound: 1288.46425

In [50]:
outliers = long_df[long_df["Sales"] > upper_bound]

outliers.shape

(70, 5)

In [51]:
outliers.head(20)

           Order ID Order Date     Ship Mode      Segment     Sales
16   CA-2012-137974 2014-04-16   First Class     Consumer  2298.900
24   CA-2013-110492 2015-02-12   First Class     Consumer  1366.040
37   CA-2014-103212 2016-10-13   First Class     Consumer  1541.510
55   CA-2014-158729 2016-12-19   First Class     Consumer  1665.620
76   CA-2011-124688 2013-08-27   First Class    Corporate  1812.010
82   CA-2012-121720 2014-06-11   First Class    Corporate  3165.744
90   CA-2013-133711 2015-11-27   First Class    Corporate  3236.410
102  CA-2014-147760 2016-11-04   First Class    Corporate  1883.724
113  CA-2011-136567 2013-12-20   First Class  Home Office  2884.370
123  US-2014-162558 2016-10-02   First Class  Home Office  2437.672
134  CA-2013-105256 2015-05-21      Same Day     Consumer  1363.960
156  US-2014-168116 2016-11-04      Same Day    Corporate  8167.420
162  US-2013-108504 2015-02-05      Same Day  Home Office  2075.510
168  CA-2011-120768 2013-12-19  Second Class     Consumer  1979.890
173  CA-2011-132612 2013-06-09  Second Class     Consumer  1441.300
185  CA-2012-116638 2014-01-28  Second Class     Consumer  4297.644
191  CA-2012-155600 2014-12-04  Second Class     Consumer  1635.018
209  CA-2013-158841 2015-02-02  Second Class     Consumer  8805.040
211  CA-2013-162355 2015-07-01  Second Class     Consumer  1302.830
227  CA-2014-129021 2016-08-23  Second Class     Consumer  4590.344

In [52]:
outliers.shape

(70, 5)

In [53]:
long_df["Sales"].describe()

count      822.00000
mean       476.54733
std       1144.58992
min          1.16700
25%         34.54050
50%        159.97500
75%        536.11000
max      23661.22800
Name: Sales, dtype: float64

In [54]:
long_df.groupby(["Ship Mode", "Segment"])["Sales"].sum()

Ship Mode       Segment
First Class     Consumer        20802.1730
                Corporate       20792.6070
                Home Office      7737.7860
Same Day        Consumer         8132.4090
                Corporate        9907.3080
                Home Office      2977.4560
Second Class    Consumer        49724.2545
                Corporate       35243.2310
                Home Office      8791.1270
Standard Class  Consumer       116922.1345
                Corporate       55942.7865
                Home Office     54748.6325
Name: Sales, dtype: float64

In [55]:
long_df.shape

(822, 5)

In [56]:
long_df.columns

Index(['Order ID', 'Order Date', 'Ship Mode', 'Segment', 'Sales'], dtype='object')

In [57]:
long_df.head()

         Order ID Order Date    Ship Mode   Segment    Sales
0  CA-2011-103366 2013-01-15  First Class  Consumer  149.950
1  CA-2011-109043 2013-08-15  First Class  Consumer  243.600
2  CA-2011-113166 2013-12-24  First Class  Consumer    9.568
3  CA-2011-124023 2013-04-07  First Class  Consumer    8.960
4  CA-2011-130155 2013-05-19  First Class  Consumer   34.200

In [58]:
long_df.to_csv("Book2data.csv", index=False)

In [59]:
pd.read_csv("Book2data.csv").shape

(822, 5)